# File: .github/workflows/hugo.yml

name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Thay bằng nhánh bạn dùng, ví dụ: master nếu dùng nhánh master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Nếu bạn dùng theme Hugo dưới dạng submodule

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Sử dụng phiên bản Hugo mới nhất

      - name: Build site
        run: hugo --minify  # Build site với chế độ tối ưu hóa

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Thư mục public được tạo bởi Hugo
